#!/usr/bin/env python3
"""Growth Hub — full-site search index builder.

Walks every .html page in the repo (except index.html), extracts its title and
visible text, and writes assets/search-index.js. The index powers the "Across
the Hub" results in the home-page search bar.

Run from the repo root any time pages are added or meaningfully edited:

    python3 build-search-index.py

Then commit/upload BOTH the new page(s) and the regenerated
assets/search-index.js — same rule as index.html card edits.
"""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "assets" / "search-index.js"
MAX_CHARS = 20000  # per-page text cap

SECTION_LABELS = [
    ("tools/engage/", "Engage Play"),
    ("tools/plays/", "Growth Hub Play"),
    ("tools/wire/", "The Wire"),
    ("tools/", "Development"),
    ("resources/", "Resource"),
    ("story/", "Who We Are"),
    ("how/", "How We Work"),
    ("field", "The Field"),
    ("plays/", "Solutions"),
]


def section_label(rel: str) -> str:
    for prefix, label in SECTION_LABELS:
        if rel.startswith(prefix):
            return label
    return "Hub"


def extract(path: Path):
    raw = path.read_text(encoding="utf-8", errors="replace")
    title_m = re.search(r"<title[^>]*>(.*?)</title>", raw, re.S | re.I)
    title = html.unescape(re.sub(r"\s+", " ", title_m.group(1))).strip() if title_m else path.stem
    # Strip non-visible content, then tags.
    body = re.sub(r"<(script|style|noscript|template)\b.*?</\1>", " ", raw, flags=re.S | re.I)
    body = re.sub(r"<!--.*?-->", " ", body, flags=re.S)
    body = re.sub(r"<[^>]+>", " ", body)
    body = html.unescape(body)
    text = re.sub(r"\s+", " ", body).strip()
    return title, text[:MAX_CHARS]


def main():
    pages = []
    for p in sorted(ROOT.rglob("*.html")):
        rel = p.relative_to(ROOT).as_posix()
        if rel == "index.html":
            continue
        title, text = extract(p)
        pages.append({"u": rel, "t": title, "s": section_label(rel), "x": text})
    # One page per line: a single 200 KB line breaks copy-paste and web editors,
    # so the array is written with each entry on its own line.
    lines = ",\n".join(json.dumps(p, ensure_ascii=False, separators=(",", ":")) for p in pages)
    OUT.write_text(
        "// Generated by build-search-index.py — do not hand-edit. Regenerate when pages change.\n"
        "window.GH_SEARCH_INDEX = [\n" + lines + "\n];\n",
        encoding="utf-8",
    )
    kb = OUT.stat().st_size / 1024
    print(f"Indexed {len(pages)} pages -> {OUT.relative_to(ROOT)} ({kb:.0f} KB)")


if __name__ == "__main__":
    main()
